version: "3.8"
services:
  backend:
    image: 172.19.136.127:8083/nodemongoapp:1.0.0
    restart: always
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    image: 172.19.136.127:8083/reactapp:1.0.0
    restart: always
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"