version: "3.8"
services:
  backend:
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"